# Generated by Django 5.0.6 on 2025-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='flagged_date',
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
